import React from 'react';
import Settings from '@/config/settings';
import { Html, Head, Main, NextScript } from 'next/document';

/**
 * DOM基底構成
 * @return {React.FunctionComponent}
 */
const Document: React.FunctionComponent = () => {
  const url = Settings.document.url;
  const title = Settings.document.title;
  const description = Settings.document.description;

  return (
    <Html lang={Settings.document.lang}>
      <Head>
        {/* Change the contents of `<Head>` as needed. */}
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content={description} />
        <meta name="theme-color" content="#333" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content={title} />
        <meta property="og:url" content={url} />
        <meta property="og:description" content={description} />
        <meta property="og:site_name" content={title} />
        <meta property="og:image" content={`${url}/ogp.png`} />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="format-detection" content="telephone=no" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
};

export default Document;
